export const supplyOrderData = [
  {
    name: "Jeff Klein",
    order: "101",
    location: "West Building",
    created: "02/12/2022",
    desiredDate: "01/28/2022",
    status: "OPEN",
  },
  {
    name: "Bill Jones",
    order: "102",
    location: "East Building",
    created: "04/12/2022",
    desiredDate: "04/28/2022",
    status: "CLOSED",
  },
  {
    name: "Jerry Jones",
    order: "102",
    location: "East Building",
    created: "04/12/2022",
    desiredDate: "04/28/2022",
    status: "CLOSED",
  },
  {
    name: "Sam Smith",
    order: "102",
    location: "East Building",
    created: "04/12/2022",
    desiredDate: "04/28/2022",
    status: "CLOSED",
  },
];

export const employeeData = [
  {
    employeeId: "101",
    employeeName: "Jeff Klein",
    position: "Maintenance Manager",
    department: "Maintenance",
    email: "jklein@gmail.com",
    phone: "(231)796-5443",
  },
  {
    employeeId: "204",
    employeeName: "Cobb Steward",
    position: "Grounds I",
    department: "Maintenance",
    email: "cstew@gmail.com",
    phone: "(231)831-1991",
  },
  {
    employeeId: "308",
    employeeName: "Todd Stewart",
    position: "Grounds II",
    department: "Maintenance",
    email: "tstewart@gmail.com",
    phone: "(231)503-1355",
  },
  {
    employeeId: "491",
    employeeName: "Ted Koppel",
    position: "Custodial Manager",
    department: "Custodial",
    email: "koppelt@gmail.com",
    phone: "(231)491-9392",
  },
  {
    employeeId: "212",
    employeeName: "Mike Shoemaker",
    position: "Custodian II",
    department: "Custodial III",
    email: "mshoemaker@gmail.com",
    phone: "(231)431-0349",
  },
];
